### PR TITLE
Add support to .env files

### PR DESCRIPTION
**Pull request by jonathansp**
pydantic _BaseSetting_ can make use of _.env_ files to set up its env vars. This PR enables the use of _.env_ file for MLServer.

```
# .env
MLSERVER_MODEL_NAME=...
MLSERVER_MODEL_IMPLEMENTATION=...
```

### CODE REVIEW

**Review by Rendson-RFernandes — APPROVED** [review]

**Review by Rendson-RFernandes — COMMENTED** [review]
.

**Comment by jonathansp** [comment]
@adriangonz can you please have a look if it makes sense?

**Review by adriangonz — COMMENTED** [review]
Hey @jonathansp ,

That's a great addition! This could be helpful for folks already using `.env` files. 

Doesn't this need some extra deps though? Looking at the [Pydantic docs](https://pydantic-docs.helpmanual.io/usage/settings/#dotenv-env-support), it looks like the `python-dotenv` package also needs to be present, right? 

Would it make sense to add some tests to ensure the settings get loaded from an `.env` file if present?

**Comment by adriangonz** [comment]
Hey @jonathansp ,

Just following up from my previous message, have you had a chance to checkout the comments above? We're starting to close the final things before the `1.1.0` release, and it would be great to get this PR in as well!

**Comment by jonathansp** [comment]
hey @adriangonz I've added a small test case to cover this feature. Also, I added _python-dotenv_ to setup.py as you mentioned and described at https://pydantic-docs.helpmanual.io/usage/settings/#dotenv-env-support. Please let me know if anything else needs to be added.

**Comment by adriangonz** [comment]
It looks like the linter pipeline is failing.  Could you have a quick look? You can also run it locally with `make lint` BTW.

```
./tests/test_settings.py:23:27: E712 comparison to True should be 'if cond is True:' or 'if cond:'
```

There're also some failures coming from the tests, but those seem to be unrelated to this PR. There were a couple flaky tests which have now been sorted out in `master`, so feel free to ignore those errors.

**Comment by jonathansp** [comment]
done @adriangonz 👍

**Comment by jonathansp** [comment]
hey @adriangonz, any ETA for 1.11 release?

**Comment by adriangonz** [comment]
Hey @jonathansp ,

This PR should be present on the `1.1.0` release, which has already been published.

**Pull request merged**
